<?php

/**
 * Implements hook_menu().
 */
function nurani_library_ui_menu() {
  $items = array();
  $items['ajax/picker-ui'] = array(
    'title' => 'Nurani Library Picker UI',
    'page callback' => 'nurani_library_ui_picker_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu callback, prints Javascript code suitable to initialize a new
 * Nurani Library picker UI.
 */
function nurani_library_ui_picker_ajax() {
  // $settings = array(
  //   'selector' => isset($_GET['selector']) ? $_GET['selector'] : '#nurani-library-picker',
  // );

  // $output  = '';
  // $output .= '(function ($) {';
  // $output .=   '';
  // $output .= '}(jQuery));';

  return NULL;
}