<?php

/**
 * Implements hook_menu().
 */
function nurani_library_ui_menu() {
  $items = array();
  $items['nurani-library'] = array(
    'title' => 'Nurani Library',
    'page callback' => 'nurani_library_ui',
    'access arguments' => array('access nurani library ui'),
    'file' => 'nurani_library_ui.pages.inc',
  );
  $items['nurani-library/picker-ui'] = array(
    'title' => 'Nurani Library Picker UI',
    'page callback' => 'nurani_library_ui_picker_ui',
    'access arguments' => array('access nurani library ui'),
    'file' => 'nurani_library_ui.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function nurani_library_ui_permission() {
  return array(
    'access nurani library ui' =>  array(
      'title' => t('Access the Nurani Library Interface'),
    ),
  );
}
